version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
build:
  verbosity: minimal
before_package:
- ps: "Copy-Item C:\\projects\\Platformer_DevelopmentClass\\$env:CONFIGURATION\\Motor2D.exe \nC:\\projects\\Platformer_DevelopmentClass\\Game\\"
artifacts:
- path: /Game
  name: release
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: 4m9ajWwuB9rba+rrj0zg+6RZCacOu4d+ytuF7VN58NS03B8vdBb1oZXtIE/mivAb69ZjE3CG3Leu+nX4FtvfWpPlgaFMDO2MWN8di23jWpw=
  draft: true